version: "3.9"

services:
  fastapi_app:
    build:
      context: .  # Контекст сборки — корень проекта (видит requirements.txt)
      dockerfile: ./app/Dockerfile  # Путь к Dockerfile внутри папки app
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app  # Монтирование только папки app (для разработки)
    restart: always

  aiogram_bot:
    build:
      context: .  # Корень проекта
      dockerfile: ./tg_admin_bot/Dockerfile
    container_name: aiogram_bot
    volumes:
      - ./tg_admin_bot:/app  # Монтирование только папки tg_admin_bot
    restart: always
    depends_on:
      - fastapi_app  # Ждём запуска FastAPI