version: "3.9"

services:
  fastapi_app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./database:/database  # Монтируем как отдельную корневую папку
    environment:
      - PYTHONPATH=/:/app:/database  # Добавляем /database в PYTHONPATH
    restart: always

  aiogram_bot:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./tg_admin_bot/Dockerfile
    container_name: aiogram_bot
    volumes:
      - ./tg_admin_bot:/app
      - ./database:/database  # Монтируем как отдельную корневую папку
    environment:
      - PYTHONPATH=/:/app:/database  # Добавляем /database в PYTHONPATH
    restart: always
    depends_on:
      - fastapi_app