"""Подправил БД User модель

Revision ID: cdc89b80cce3
Revises: a9c2a743d12a
Create Date: 2025-07-11 01:36:20.330726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc89b80cce3'
down_revision: Union[str, Sequence[str], None] = 'a9c2a743d12a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'city')
    op.drop_column('users', 'mood')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('mood', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('city', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
